// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrnkwxdijodfdppfjors.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFybmt3eGRpam9kZmRwcGZqb3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjIzMDIsImV4cCI6MjA2MjE5ODMwMn0.QZW7Im_qxhyf3bOeVVDlSwUidRxCE3IY4aScKZyyx3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);