
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import env from '@/config/environment';

// Use environment variables with fallbacks
const SUPABASE_URL = env.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = env.supabaseAnonKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add error handling helpers for Supabase operations
export const handleSupabaseError = (error: any, fallbackMessage = 'An error occurred') => {
  console.error('Supabase error:', error);
  return {
    message: error?.message || fallbackMessage,
    status: error?.status || 500,
    details: error?.details || null
  };
};
